spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/pfe?createIfNotExist=true

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

